### ISSUE TITLE
Sequence Builder Smart Highlight 

### ISSUE THREAD

**Issue by metzdigital** [nasa/fprime-gds#14]
| | |
|:---|:---|
|**_F´ Version_**| |
|**_Affected Component_**|   |
---
## Problem Description

A description of the problem with sufficient detail to understand the issue.

## How to Reproduce

1. 
2.
3.

## Expected Behavior

A description of the expected behavior.
When highlighting text the visualizer for the text gets out of whack and starts displaying erroneous characters:
https://user-images.githubusercontent.com/2592986/128091354-8a5cb0a2-d117-4af0-b413-a8c67737c677.png

**Comment by LeStarch** [comment]
Cannot really fix this, as it is an underlying problem with the library we use.

**Comment by metzdigital** [comment]
Shall I close the issue?

**Comment by LeStarch** [comment]
Yeah, we can close it.
