### ISSUE TITLE
Fix UI responsive issues

### ISSUE THREAD

**Issue by saba-ja** [nasa/fprime-gds#18]
| | |
|:---|:---|
|**_F´ Version_**| F' GDS 2.0 |
|**_Affected Component_**|  JS  |
---
## Problem Description

The current UI has many responsive issues that should be fixed.
1- Buttons do not change size and location on smaller screens
2- [DOM] Found 2 elements with non-unique id #command-text
3- DevTools failed to load source map: Could not load content for *.css.map or *.js.map
4- Navbar expands to a very long vertical list in md size
5- Unclosed HTML tags in different parts of the GDS

## How to Reproduce

1. Start GDS
2. Resize window and observe HTML elements placement
3. Open chrome dev tool and see Devtool warnings

## Expected Behavior
Responsive HTML behavior on resize, and no JS or HTML warning or error.

**Comment by LeStarch** [comment]
Says it was merged. Closing.
