### ISSUE TITLE
Command Drop Down Resumes

### ISSUE THREAD

**Issue by metzdigital** [nasa/fprime-gds#28]
| | |
|:---|:---|
|**_F´ Version_**| |
|**_Affected Component_**|  |
---
## Feature Description

Can we make the command drop down resume where you last were when you click the drop down? I always hate that it goes back to the top so I have to scroll all the way back down to get back where I was.

![image](https://user-images.githubusercontent.com/2592986/131039407-caa120f2-0e68-4366-a37b-fe41cd62cf1b.png)

**Comment by LeStarch** [comment]
This is another one that is caused by third party code.
