### ISSUE TITLE
VxWorks connection issues

### ISSUE THREAD

**Issue by timcanham** [nasa/fprime-gds#29]
| | |
|:---|:---|
|**_F´ Version_**| v2.0.0 |
|**_Affected Component_**| n/a   |
---
## Problem Description

We frequently get these messages on VxWorks:

```
-> 0x203cf2f8 (TV_ELOG): [ERROR] Failed to send framed data: 0
0x203cf2f8 (TV_ELOG): [ERROR] Failed to send framed data: 0
0x203cf2f8 (TV_ELOG): [ERROR] Failed to send framed data: 0
0x203cf2f8 (TV_ELOG): [ERROR] Failed to send framed data: 0
0x203cf2f8 (TV_ELOG): [ERROR] Failed to send framed data: 0
0x203cf2f8 (TV_ELOG): [ERROR] Failed to send framed data: 0
0x203cf2f8 (TV_ELOG): [ERROR] Failed to send framed data: 0
0x203cf2f8 (TV_ELOG): [ERROR] Failed to send framed data: 0
0x203cf2f8 (TV_ELOG): [ERROR] Failed to send framed data: 0
0x203cf2f8 (TV_ELOG): [ERROR] Failed to send framed data: 0
0x203cf2f8 (TV_ELOG): [ERROR] Failed to send framed data: 0
0x203cf2f8 (TV_ELOG): [ERROR] Failed to send framed data: 0
0x203cf2f8 (TV_ELOG): [ERROR] Failed to send framed data: 0
...
0x203f3320 (TV_ReceiveTask): Connected to �:0 as a tcp client
```

In some cases, the FSW doesn't initially connect, and it can take a minute or so to reconnect. I don't know if this unique to our case, but I wanted to capture it.

## How to Reproduce

On an internal system, so we would have to show it.

## Expected Behavior

Clean first-time and secondary connections.

**Comment by Joshua-Anderson** [comment]
You can see this behavior in the Ref app as well. The TCP client will print errors until it can connect to the GDS. Maybe we should only warn about failing to send after the initial connection?

**Comment by timcanham** [comment]
That would make sense. What we're seeing sometimes is that even after the "Connected to" EVR, it can take a minute or so to REALLY connect.

**Comment by LeStarch** [comment]
This isn't a GDS issue. This is an fprime issue.
