### ISSUE TITLE
Layout of the GDS image link leads to 404

### ISSUE THREAD

**Issue by Emil808** [nasa/fprime-gds#39]
| | |
|:---|:---|
|**_F´ Version_**| |
|**_Affected Component_**| fprime-community/fprime-gds/README.md  |
---
## Problem Description

Image link "The layout of the GDS" leads to Page Not Found. 

## How to Reproduce

1. Follow "The layout of the GDS" in fprime-gds/README.md

## Expected Behavior

Shows an image of the layout of the GDS.

**Comment by thomas-bc** [comment]
Fixed by https://github.com/fprime-community/fprime-gds/pull/110
