### ISSUE TITLE
Update GDS to support multiple telemetry channels in downlink packet

### ISSUE THREAD

**Issue by timcanham** [nasa/fprime-gds#40]
| | |
|:---|:---|
|**_F´ Version_**| v3.0 |
|**_Affected Component_**| GDS? |
---
## Feature Description

Update GDS telemetry decoder to accept multiple channels in a packet. It would have to use the dictionary to decode each channel entry based on the size of the type, and then advance to the next channel until reaching the end of the packet.

Paired with:  https://github.com/nasa/fprime/issues/1204
This issue must be done first.

## Rationale

This will fill downlink packets more efficiently.

**Comment by LeStarch** [comment]
Moved already:
