### ISSUE TITLE
Missing diagram link

### ISSUE THREAD

**Issue by timcanham** [nasa/fprime-gds#44]
| | |
|:---|:---|
|**_F´ Version_**| 3.x |
|**_Affected Component_**| n/a  |
---
## Problem Description

There is a broken link pointing to a diagram

## How to Reproduce

See the README:

![image](https://user-images.githubusercontent.com/8086374/155008275-bcb6fd8f-3dfa-4b96-8776-14a858ad97a6.png)

## Expected Behavior

Link should have a image.

**Comment by thomas-bc** [comment]
Fixed by https://github.com/fprime-community/fprime-gds/pull/110
