### ISSUE TITLE
Missing documentation link

### ISSUE THREAD

**Issue by timcanham** [nasa/fprime-gds#45]
| | |
|:---|:---|
|**_F´ Version_**| 3.x |
|**_Affected Component_**|  n/a |
---
## Problem Description

There are some broken links in the README documentation:

## How to Reproduce

See the documentation and user's guide links.

![image](https://user-images.githubusercontent.com/8086374/155008462-6bb9a99d-0a6f-4768-884a-bb028a5b433f.png)

## Expected Behavior

A description of the expected behavior.

**Comment by thomas-bc** [comment]
Fixed by https://github.com/fprime-community/fprime-gds/pull/110
