### ISSUE TITLE
Green "data present" icon does not return to red after FSW stops transmitting.

### ISSUE THREAD

**Issue by timcanham** [nasa/fprime-gds#47]
| | |
|:---|:---|
|**_F´ Version_**| 3.x |
|**_Affected Component_**| n/a  |
---
## Problem Description

When the FSW stops transmitting data, the green "data received" light does not transition to red again.

## How to Reproduce

1. Build Ref demo app
2. Run GDS without starting binary: `fprime-gds -n`
3. Run binary manually: `./build-fprime-automatic-native/bin/Linux/Ref -p 50000 -a 0.0.0.0`
4. Kill binary with Ctrl-C
5. Green light stays lit

## Expected Behavior

The green icon should transition to red after a timeout, and then become green again if the binary is restarted.

**Comment by LeStarch** [comment]
Fixed
